### ADD_PRODUCT
POST http://localhost:8082/seller/product
Content-Type: application/json
X_AUTH_TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocHdQK2lwOFp6SmVNbzMyWkMwWmpGazI4K3dsZWU5MEV5VkZsaWdCalVnPSIsImp0aSI6IjVlMy81S3JMU2NGY1JqOUNhQVVHWlE9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2Njk0NTM2MzYsImV4cCI6MTY2OTU0MDAzNn0.pKnBLLHE2EAJx4L0Ug435xYytdwhrelfixWQ7u2Ja4M


{
  "name": "name",
  "description": "description",
  "addProductItemFormList": [
    {
      "name": "productName",
      "price": 1000,
      "count": 1
    },
    {
      "name": "productName2",
      "price": 2000,
      "count": 2
    }
  ]
}

### ADD_PRODUCT_ITEM
POST http://localhost:8082/seller/productItem
Content-Type: application/json
X_AUTH_TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocHdQK2lwOFp6SmVNbzMyWkMwWmpGazI4K3dsZWU5MEV5VkZsaWdCalVnPSIsImp0aSI6IjVlMy81S3JMU2NGY1JqOUNhQVVHWlE9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY5NDY0MDg3LCJleHAiOjE2Njk1NTA0ODd9.yREPI3g9wLmBEng4-24I0cRFUmoO5RZiDLjMjISzTro

{
  "productId": 8,
  "name": "productItem99",
  "price": 50000,
  "count": 3
}

### UPDATE_PRODUCT_ITEM
PUT http://localhost:8082/seller/updateProductItem
Content-Type: application/json
X_AUTH_TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocHdQK2lwOFp6SmVNbzMyWkMwWmpGazI4K3dsZWU5MEV5VkZsaWdCalVnPSIsImp0aSI6IjVlMy81S3JMU2NGY1JqOUNhQVVHWlE9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY5NDY0MDg3LCJleHAiOjE2Njk1NTA0ODd9.yREPI3g9wLmBEng4-24I0cRFUmoO5RZiDLjMjISzTro

{
  "id": 7,
  "name": "productName!!!!",
  "count": 5,
  "price": 1000
}

### UPDATE_PRODUCT_ITEM
PUT http://localhost:8082/seller/updateProduct
Content-Type: application/json
X_AUTH_TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocHdQK2lwOFp6SmVNbzMyWkMwWmpGazI4K3dsZWU5MEV5VkZsaWdCalVnPSIsImp0aSI6IjVlMy81S3JMU2NGY1JqOUNhQVVHWlE9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY5NDY0MDg3LCJleHAiOjE2Njk1NTA0ODd9.yREPI3g9wLmBEng4-24I0cRFUmoO5RZiDLjMjISzTro

{
  "id": 4,
  "sellerId": 1,
  "name": "name!!~!",
  "description": "description!!",
  "updateProductItemForms": [
    {
      "id": 7,
      "name": "productName!!!!",
      "count": 1,
      "price": 1000
    },
    {
      "id": 8,
      "name": "productName22!!",
      "count": 20,
      "price": 20000
    },
    {
      "id": 9,
      "name": "nike",
      "count": 5,
      "price": 200000
    }
  ]
}

### DELETE_PRODUCT
DELETE http://localhost:8082/seller/deleteProduct?id=10
X_AUTH_TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocHdQK2lwOFp6SmVNbzMyWkMwWmpGazI4K3dsZWU5MEV5VkZsaWdCalVnPSIsImp0aSI6IjVlMy81S3JMU2NGY1JqOUNhQVVHWlE9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY5NDY0MDg3LCJleHAiOjE2Njk1NTA0ODd9.yREPI3g9wLmBEng4-24I0cRFUmoO5RZiDLjMjISzTro


### DELETE_PRODUCT_ITEM
DELETE http://localhost:8082/seller/deleteProductItem?id=30
X_AUTH_TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocHdQK2lwOFp6SmVNbzMyWkMwWmpGazI4K3dsZWU5MEV5VkZsaWdCalVnPSIsImp0aSI6IjVlMy81S3JMU2NGY1JqOUNhQVVHWlE9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY5NDY0MDg3LCJleHAiOjE2Njk1NTA0ODd9.yREPI3g9wLmBEng4-24I0cRFUmoO5RZiDLjMjISzTro

### SEARCH_PRODUCT
GET http://localhost:8082/search/product?name=name
X_AUTH_TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocHdQK2lwOFp6SmVNbzMyWkMwWmpGazI4K3dsZWU5MEV5VkZsaWdCalVnPSIsImp0aSI6IjVlMy81S3JMU2NGY1JqOUNhQVVHWlE9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY5NTM1OTk0LCJleHAiOjE2Njk2MjIzOTR9.RJeit-sc9oa79gDB6CZ2QNlH4NlD_fVMyZSQ5StknyQ

### SEARCH_PRODUCT_DETAILS
GET http://localhost:8082/search/product/details?id=13
X_AUTH_TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJocHdQK2lwOFp6SmVNbzMyWkMwWmpGazI4K3dsZWU5MEV5VkZsaWdCalVnPSIsImp0aSI6IjVlMy81S3JMU2NGY1JqOUNhQVVHWlE9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY5NTM1OTk0LCJleHAiOjE2Njk2MjIzOTR9.RJeit-sc9oa79gDB6CZ2QNlH4NlD_fVMyZSQ5StknyQ